
title: My Resume
url: 'http://hansyao.github.io'
baseurl: '/myresume' #change it according to your repository name



# Profile information
yourname: Hans Yao  ## put your name
title: 'Finance Manager &amp; Software Enginner'  ## your title
location: Shanghai, China


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  