
title: My Resume
url: http://hansyao.github.io
baseurl: '/myresume' #change it according to your repository name


# Profile information
yourname: Hans Yao  ## put your name
title: 'Finance Manager &amp; Software Enginner'  ## your title
location: Shanghai, China
dateofbirthday: Jun 27, 1977
address: 41-902, 1028 Xiuyang Road, Pudong, Shanghai, China
email: hansyow@gmail.com
phone: +1(857)288-8870
skype: hans.yao
gdrive: hansyow@gmail.com
skydrive: hansyow@gmail.com
wechat: hans1977


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
# dribbble: http://hansyao.github.io  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url
myblog: https://hansyao.github.io ## your blog url



# Update all the sections by editing the files inside _includes folder.


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  